### ISSUE TITLE
vendor.yml file

### ISSUE THREAD

**Issue by smousa** [govend/govend#21]
How do I only update the affected dependencies that have updated commit hashes in the vendor.yml file?

**Comment by jackspirou** [comment]
@smousa if you run `govend -v -u github.com/smosa/project` github.com/smosa/project will be updated along with any of its deps.  

If you want to update to a particular revision hash you can do the following: 
1. update the `vendor.yml` file to that revision sha you want
2. remove that particular package directory under `vendor`
3. run `govend -v` again and it will pick up the new revision hash in `vendor.yml`. 

Does that answer your question?

**Comment by jackspirou** [comment]
@smousa also please run `go get -u github.com/govend/govend` to get the latest version.  `govend` has been under some rapid development lately.

**Comment by jackspirou** [comment]
@smousa in the gitter room we were just discussing adding better documentation around the `vendor.yml` and updating deps.  Maybe that will help.

**Comment by jackspirou** [comment]
@smousa im going to close this issue, but since the readme has been updated I think we have some better docs around your question.  If you feel otherwise, your feedback is welcome.
