### ISSUE TITLE
Running travis's go tip verision fails with govend

### ISSUE THREAD

**Issue by MetalMatze** [govend/govend#38]
Hey govend fails when trying to run on travis-ci.
It seems to be related to the go tip version which is not semver.

https://travis-ci.org/MetalMatze/warp/jobs/117053487

**Comment by jackspirou** [comment]
@MetalMatze you hit the nail on the head.  At https://github.com/govend/govend/blob/master/deps/vendorable.go#L42 the result of `runtime.Version()` grabs a tag if possible.  If not possible the commit hash is returned.  So go tip returns a commit hash.

**Comment by jackspirou** [comment]
@MetalMatze I pushed a patch to trust the current running version of Go, if we cannot parse the output of `runtime.Version()` as a valid semver.  This should fix the issues with travis tests on the tip version of Go. 

Does this solution seem good for your use case?

**Comment by MetalMatze** [comment]
Yup. This is the fix for my problem.
https://travis-ci.org/MetalMatze/warp/jobs/117144347
