### ISSUE TITLE
Vendorable Checks argv[0] Against GOPATH/src

### ISSUE THREAD

**Issue by swdunlop** [govend/govend#42]
The following code from `Vendorable` in `deps/vendorable.go` checks `os.Args[0]` (which is the path to the govendor binary) against `$GOPATH/src`.  This means it will not work for any project unless you are invoking `./govendor` where your current directory is within `$GOPATH/src`.

```go
   // check the env $GOPATH is valid
    gopath := os.Getenv("GOPATH")
    if len(gopath) == 0 {
        log.Fatal(errors.New("please set your $GOPATH"))
    }

    // determine the current absolute file path
    path, err := filepath.Abs(filepath.Dir(os.Args[0]))
    if err != nil {
        log.Fatal(err)
    }

    // check we are in the $GOPATH
    if !strings.Contains(path, gopath+"/src/") {
        return errors.New("you cannot vendor packages outside of your $GOPATH/src")
    }
```

Reproduction:

```
$ mkdir -p /tmp/go/src 
$ cd /tmp/go/src 
$ env GOPATH=/tmp/go ~/bin/govend
```

This will result in "you cannot vendor packages outside of your $GOPATH/src"

**Comment by swdunlop** [comment]
Similarly, in `projectImportPath`

```
    path, err := filepath.Abs(filepath.Dir(os.Args[0]))
```

**Comment by jackspirou** [comment]
@swdunlop  The command `go get -u github.com/govend/govend` will place the `govend` binary in your `$GOPATH/bin` directory and the `$GOPATH/bin` directory is usually in ones `$PATH` so this is not an issue. 

Is the issue here that this error message appears when invoking `govend` by a directory path rather than by the `$PATH` env variable?

**Comment by swdunlop** [comment]
That is strange and unexpected for me.  As a new user of `govend`, I expected a check to see if `$GOPATH/src` is the prefix of the current working directory, with the assumption that `govend` is checking that my source lives in a proper `GOPATH` as a sanity check.  This assumption was supported by the error message, `you cannot vendor packages outside of your $GOPATH/src`.

By my reading of `Vendorable`, the check will only succeed if I invoked `govend` by `$GOPATH/src/$ANOTHERDIR/govend` (and not `$GOPATH/bin/govend` from your comment).  This is because `filepath.Dir` cleans off any trailing `/`, so to match `$GOPATH/src/`, there must be at least one directory between `src` and `govend`.

**Comment by swdunlop** [comment]
Oh. And it's also not Windows safe, due to their wretched `\`, but that may be a feature. :)

**Comment by jackspirou** [comment]
@swdunlop sorry for the confusion, I think we are saying the same thing (but let me confirm): 

* `$ ./$GOPATH/bin/govend -vlt` will not work today given the reasons you have outlined
* while `$PATH` contains `$GOPATH/bin` and you are currently located in `$GOPATH/src/*` the command `$ govend -vlt` will work

I think you have brought up two points we can fix: 
1. `govend` should check the working directory for `$GOPATH/src/`, not the current directory of the `govend` binary for `$GOPATH/src/`
2. you are right, this method is not safe for windows :)

**Comment by swdunlop** [comment]
I think that's it exactly.  Happy to put together a pull request in the morning.

**Comment by jackspirou** [comment]
That would be great!  Thanks very much for pointing both of these issues and offering to help with a PR :+1:

**Comment by jackspirou** [comment]
PR #43 closes this issue.  Thanks again @swdunlop !
