### ISSUE TITLE
checkGopath in Windows

### ISSUE THREAD

**Issue by serbe** [govend/govend#53]
When using govend under Windows always gives an error: "you can not vendor packages outside of your $GOPATH/src". This is due to the different register VolumeName.
I run govend from the folder D:\gopath\src\github.com. The result is:
`gopath := os.Getenv("GOPATH") // == d:\gopath`
`cwd, _ := os.Getwd() // == D:\gopath\src\github.com`
`_ = filepath.VolumeName(gopath) // == d:`
`_ = filepath.VolumeName(cwd) // == D:`
Change the variable $GOPATH on D:\gopath solved the problem, but the use of other tools such problems did not arise.
Maybe add
`if runtime.GOOS == "windows" {`
`gosrc = strings.ToLower(gosrc)`
`cwd = strings.ToLower(cwd)`
`}`
before
`if !strings.HasPrefix(cwd, gosrc) {`

**Comment by nicolapetracchi** [comment]
Same issue here, you can try with my solution:

`// check $GOPATH/src
gosrc := filepath.Join(gopath, "src") + string(filepath.Separator)
gosrc, err = filepath.EvalSymlinks(gosrc)    // <== kind of "normalization", drive letter from lowercase to upper for some reason and perhaps some others modifications for certain paths
if err != nil { .....`
